two_wheel_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 

  # Effort Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Left_wheel_Joint 
    pid: {p: 100, i: 0.01, d: 10}
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Right_wheel_Joint
    pid: {p: 100, i: 0.01, d: 10}

